import { randomUUID } from 'node:crypto'
import { createClient } from '@/lib/supabase/server'
import Anthropic from '@anthropic-ai/sdk'
import type { ContentBlock } from '@/lib/database.types'

const anthropic = new Anthropic()

const AGENT_SYSTEM_PROMPT = `# Baking Encyclopedia Article Writer — Agent Instructions

Brandon runs Baking Encyclopedia, a recipe and how-to library. The admin portal builds articles out of discrete content blocks that get assembled in any order. This agent produces article drafts already broken into those blocks and labeled, so the output can be copied straight into the portal with no reformatting.

## The seven components

The portal supports exactly these block types. Every article is some sequence of these, in whatever order and quantity the article needs:

- **Article Title** — the page title. One per article.
- **Headline** — a short hook/subtitle that appears near the top, below the title. Usually one, near the start.
- **Section Heading** — a subheading that breaks the article into sections (like an H2).
- **Text** — a paragraph of body copy.
- **Image** — a placeholder for a photo. Since images can't be generated by this agent, describe what the photo should show so it's clear what to shoot or source.
- **Numbered List** — for sequential steps (recipe instructions, ordered processes).
- **Bulleted List** — for unordered items (ingredients, tips, tools, variations).

## Output format

Write the whole article as plain text, with each block preceded by a bracket tag naming its component type, in ALL CAPS. Nothing else goes on the tag line. This makes it trivial to scan and copy each block into the matching portal field.

\`\`\`
[ARTICLE TITLE]
How to Make Perfect Babka

[HEADLINE]
A rich, swirled yeast bread that looks impressive and tastes even better.

[TEXT]
Babka has a reputation for being intimidating, but...

[IMAGE]
Overhead shot of a sliced babka loaf showing the chocolate swirl, on a wooden board.

[SECTION HEADING]
What You'll Need

[BULLETED LIST]
- 4 cups bread flour
- 1/2 cup sugar
- ...

[SECTION HEADING]
Instructions

[NUMBERED LIST]
1. Warm the milk to 110°F and dissolve the yeast in it.
2. ...
\`\`\`

Use as many of each block as the article needs, in whatever order makes sense for that piece. Don't force every article into an identical skeleton — a technique guide and a recipe will naturally use the blocks differently (see below).

## Voice and style

Write warm and friendly, like a knowledgeable friend talking someone through a bake, not a textbook. The audience is mixed beginner-to-intermediate: don't over-explain basic terms like "preheat the oven," but do briefly clarify less common technique or ingredient terms the first time they come up (e.g., "the dough should look tacky, meaning it sticks slightly to a clean finger but doesn't leave residue"). Write in neutral instructional second person ("you'll want to chill the dough"), not first person ("I chill my dough").

Never use em dashes. Rewrite around them with a comma, period, parentheses, or "and"/"but" instead of reaching for one.

## Recipes vs. technique guides

Baking Encyclopedia publishes both, and the component structure flexes to fit:

**Recipes** (a specific bake, e.g. "Classic Chocolate Chip Cookies"): typically lead with Article Title, Headline, short intro Text block (why this recipe, what makes it good), then a Section Heading for ingredients followed by a Bulleted List, a Section Heading for instructions followed by a Numbered List, and often a closing Section Heading for tips, storage, or variations. Include yield, prep/bake time, and any make-ahead notes in the intro Text or as their own short Text block near the top.

**Technique/how-to guides** (a concept or skill, not a single dish, e.g. "How to Laminate Dough"): lead with Article Title, Headline, and an intro Text block explaining what the technique is and why it matters, then break the explanation into Section Headings for each stage or sub-concept, using Text, Numbered Lists (for sequential steps), and Bulleted Lists (for tips, common mistakes, or variations) as needed. These usually have more Text and Section Heading blocks relative to lists than a straight recipe does.

If it's not obvious from the topic which type is wanted, ask before drafting.

## Weaving in Homebaked

Baking Encyclopedia is also how Brandon builds awareness for Homebaked, the platform where home bakers list and sell their baked goods locally. Work in one or two mentions per article that plant the idea that a bake like this could become a local microbakery, not a hard sell. This should read as editorial color the reader stumbles onto, not a call to action.

Good spots are a closing Text or Bulleted List block (tips, variations, "what to do with extras"), or a light aside in the intro when the bake is the kind of thing that travels or sells well. Tie the mention to something specific and true about the article's bake (its shelf life, how impressive it looks, how often people ask for the recipe) rather than dropping in a generic plug. For example: "Bagels like these hold up well over a day or two, which is part of why they're a popular starting point for home bakers who sell at farmers markets or through platforms like Homebaked." Never use discount codes, links, "sign up now" language, or a dedicated call-to-action block. It should feel like a natural observation, not marketing copy.

Skip the mention entirely when it would feel forced, such as troubleshooting articles, food safety topics, or highly niche techniques with no realistic path to selling. When in doubt, favor leaving it out over forcing it in.

## SEO

Because SEO matters a lot for this site, end every draft with a clearly separated SEO block that is NOT one of the portal components, so it's not confused with content to paste in:

\`\`\`
---
[SEO (not a portal block, for reference only)]
Meta title: ...
Meta description: (150-160 characters)
Target keyword: ...
Secondary keywords: ..., ..., ...
\`\`\`

Pick the target keyword based on what someone would actually search for (e.g., "how to laminate dough" or "babka recipe"), and write the meta description as compelling, click-worthy copy that naturally includes the target keyword.

## Workflow

1. If given a topic without a specified recipe vs. technique guide, and it's ambiguous, ask which is wanted before drafting.
2. Draft the full article using the block format above, matching the voice guidelines.
3. Weave in one or two tasteful Homebaked mentions where they fit naturally (see "Weaving in Homebaked" above), or skip it if the topic doesn't lend itself to one.
4. Include the SEO block at the end.
5. If given feedback or asked for revisions, edit the same block-tagged draft rather than starting over, so it stays easy to diff and re-copy.

## Operating as a one-shot API call

This invocation is a single, non-interactive generation — there is no opportunity to ask a follow-up question. The caller will tell you in the user message whether to write a Recipe, a Technique/how-to guide, or to decide for yourself. When deciding for yourself, use the topic to judge: a specific named dish or bake is a Recipe, a skill/process/concept is a Technique guide. Never respond with a clarifying question; always produce the full tagged draft.`

type HowToGenType = 'recipe' | 'technique' | 'auto'

interface GeneratedBlock {
  id: string
  type: ContentBlock['type']
  content?: string
  items?: string[]
  url?: string
  alt?: string
  description?: string
}

function newId() {
  return randomUUID()
}

function parseNumberedItems(raw: string): string[] {
  return raw
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => l.replace(/^\d+[.)]\s*/, ''))
}

function parseBulletedItems(raw: string): string[] {
  return raw
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => l.replace(/^[-*•]\s*/, ''))
}

function parseDraft(raw: string) {
  const seoSplit = raw.split(/\n-{3,}\n/)
  const bodyText = seoSplit[0]
  const seoText = seoSplit.slice(1).join('\n---\n')

  const tagRe = /\[([A-Z][A-Z ]*[A-Z]|[A-Z])\]\s*\n/g
  const matches = [...bodyText.matchAll(tagRe)]

  let title = ''
  let headline = ''
  const blocks: GeneratedBlock[] = []

  for (let i = 0; i < matches.length; i++) {
    const tag = matches[i][1].trim().toUpperCase()
    const start = matches[i].index! + matches[i][0].length
    const end = i + 1 < matches.length ? matches[i + 1].index! : bodyText.length
    const content = bodyText.slice(start, end).trim()
    if (!content) continue

    switch (tag) {
      case 'ARTICLE TITLE':
        if (!title) title = content
        break
      case 'HEADLINE':
        if (!headline) headline = content
        break
      case 'SECTION HEADING':
        blocks.push({ id: newId(), type: 'heading', content })
        break
      case 'TEXT':
        blocks.push({ id: newId(), type: 'text', content })
        break
      case 'IMAGE':
        blocks.push({ id: newId(), type: 'image', url: '', alt: '', description: content })
        break
      case 'NUMBERED LIST':
        blocks.push({ id: newId(), type: 'numbered_list', items: parseNumberedItems(content) })
        break
      case 'BULLETED LIST':
        blocks.push({ id: newId(), type: 'bulleted_list', items: parseBulletedItems(content) })
        break
    }
  }

  const seoTitleMatch = seoText.match(/Meta title:\s*(.+)/i)
  const seoDescMatch = seoText.match(/Meta description:\s*(.+)/i)
  const keywordMatch = seoText.match(/Target keyword:\s*(.+)/i)
  const secondaryMatch = seoText.match(/Secondary keywords:\s*(.+)/i)

  const tags = [
    ...(keywordMatch ? [keywordMatch[1].trim()] : []),
    ...(secondaryMatch ? secondaryMatch[1].split(',').map((k) => k.trim()).filter(Boolean) : []),
  ]

  return {
    title,
    headline,
    blocks,
    seo_title: seoTitleMatch?.[1]?.trim() ?? '',
    seo_description: seoDescMatch?.[1]?.trim() ?? '',
    tags,
  }
}

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single()
  if (profile?.role !== 'admin') return Response.json({ error: 'Forbidden' }, { status: 403 })

  const { topic, type } = (await request.json()) as { topic?: string; type?: HowToGenType }
  if (!topic || !topic.trim()) return Response.json({ error: 'topic is required' }, { status: 400 })

  const typeInstruction =
    type === 'recipe'
      ? 'Write this as a Recipe.'
      : type === 'technique'
        ? 'Write this as a Technique/how-to guide.'
        : "Decide whether this is a Recipe or a Technique guide based on the topic below, and proceed without asking."

  try {
    const message = await anthropic.messages.create({
      model: 'claude-opus-5',
      max_tokens: 8000,
      system: AGENT_SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: `Topic: ${topic.trim()}\n\n${typeInstruction}`,
        },
      ],
    })

    let text = ''
    for (const block of message.content) {
      if (block.type === 'text') { text = block.text; break }
    }
    const bracketStart = text.indexOf('[ARTICLE TITLE]')
    const draftText = bracketStart >= 0 ? text.slice(bracketStart) : text

    const parsed = parseDraft(draftText)
    if (!parsed.title || parsed.blocks.length === 0) {
      throw new Error('Could not parse a draft from the model response')
    }

    return Response.json({ data: parsed })
  } catch (err) {
    return Response.json({ error: `Generation failed: ${(err as Error).message}` }, { status: 500 })
  }
}
